version: "3.8"

services:
  redis:
    image: redis:6.2-alpine
  web-app:
    image: celery.experiments/webapp
    build:
      context: ./
      target: webapp
    ports:
      - "127.0.0.1:8000:8000"
  worker-default:
    image: celery.experiments/worker
    build:
      context: ./
      target: worker
  worker-datasource:
    image: celery.experiments/worker
    environment:
      WORKER_QUEUE_NAME: datasource
  worker-datahandle:
    image: celery.experiments/worker
    environment:
      WORKER_QUEUE_NAME: datahandle
  worker-notification:
    image: celery.experiments/worker
    environment:
      WORKER_QUEUE_NAME: notification
