version: "3"

services:
  redis:
    image: redis:6.2-alpine
  web-app:
    image: celery.experiments:latest
    build: ./
    entrypoint: uwsgi --ini uwsgi.ini
    ports:
      - "127.0.0.1:8000:8000"
  datahandle-workers:
    image: celery.experiments:latest
    entrypoint: celery -A celery_demo.celery worker --loglevel=info --workdir /opt/app/ -Q datahandle
  datasource-workers:
    image: celery.experiments:latest
    entrypoint: celery -A celery_demo.celery worker --loglevel=info --workdir /opt/app/ -Q datasource
  notification-workers:
    image: celery.experiments:latest
    entrypoint: celery -A celery_demo.celery worker --loglevel=info --workdir /opt/app/ -Q notification
  default-queue:
    image: celery.experiments:latest
    entrypoint: celery -A celery_demo.celery worker --loglevel=info --workdir /opt/app/